#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_GOOGLE_include_directive : require

#include "gpu/shared.h"

layout(set = kRendererDescriptorSet, binding = kAccumImageBinding, rgba32f) uniform image2D accumImage;
layout(set = kRendererDescriptorSet, binding = kDisplayImageBinding, rgba8) uniform image2D displayImage;

layout(push_constant, scalar) uniform PushConstantBlock
{
    PushConstants pc;
};

void main()
{
    // gl_LaunchIDEXT (0,0) is the top-left image pixel,
    // and +y increases down the screen.
    const vec2 pixel = vec2(gl_LaunchIDEXT.xy);
    const vec2 halfResolution = vec2(gl_LaunchSizeEXT.xy) * 0.5;

    // NCHORTEK TODO: This needs to be consistent with saveImage pixel calcs
    const vec3 direction = normalize(
        pc.camera.view
        + pc.camera.right * pc.camera.pixelLength.x * (pixel.x - halfResolution.x)
        - pc.camera.up * pc.camera.pixelLength.y * (pixel.y - halfResolution.y));
    
    vec4 rayDirColor = vec4(direction * 0.5 + 0.5, 1.0);
    imageStore(displayImage, ivec2(pixel), rayDirColor);
}
